# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:02:30+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ServiceError(BaseModel):
    errorCode: Optional[str] = Field(
        None, description='The error code mapped to the error message.'
    )
    errorType: Optional[str] = Field(None, description='The category of the error.')
    message: Optional[str] = Field(
        None, description='A short explanation of the issue.'
    )
    pspReference: Optional[str] = Field(
        None, description='The PSP reference of the payment.'
    )
    status: Optional[int] = Field(None, description='The HTTP response status.')


class SubjectErasureByPspReferenceRequest(BaseModel):
    forceErasure: Optional[bool] = Field(
        None,
        description='Set this to **true** if you want to delete shopper-related data, even if the shopper has an existing recurring transaction. This only deletes the shopper-related data for the specific payment, but does not cancel the existing recurring transaction.',
    )
    merchantAccount: Optional[str] = Field(None, description='Your merchant account')
    pspReference: Optional[str] = Field(
        None,
        description='The PSP reference of the payment. We will delete all shopper-related data for this payment.',
    )


class Result(Enum):
    ACTIVE_RECURRING_TOKEN_EXISTS = 'ACTIVE_RECURRING_TOKEN_EXISTS'
    ALREADY_PROCESSED = 'ALREADY_PROCESSED'
    PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND'
    SUCCESS = 'SUCCESS'


class SubjectErasureResponse(BaseModel):
    result: Optional[Result] = Field(None, description='The result of this operation.')
